# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='expiration',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 31, 14, 14, 28, 626090)),
        ),
    ]
