# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_website_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='expiration',
            field=models.DateTimeField(default=sites.models.yearafter),
        ),
    ]
